; xdebug.ini
; Configurações para o Xdebug
zend_extension=xdebug.so
xdebug.mode=develop,debug
xdebug.start_with_request=yes
xdebug.client_host=host.docker.internal ; Para Windows/Mac com Docker Desktop
xdebug.client_port=9003
xdebug.discover_client_host=0
xdebug.idekey=VSCODE
