# Configuração do Docker Compose para a plataforma Trampix.
# Este arquivo define e orquestra os serviços (containers) necessários para o ambiente de desenvolvimento com Laravel.

version: '3.8'

services:
  # Serviço principal da aplicação, contendo PHP e Apache.
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/php/000-default.conf:/etc/apache2/sites-available/000-default.conf
    # Garante que o serviço 'db' esteja saudável (pronto) antes do 'app' iniciar
    depends_on:
      db:
        condition: service_healthy # <-- CORREÇÃO AQUI
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: trampix_db
      DB_USERNAME: user
      DB_PASSWORD: aluno
      APP_ENV: local
      APP_DEBUG: true

  # Serviço do banco de dados MySQL.
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: trampix_db
      MYSQL_USER: user
      MYSQL_PASSWORD: aluno
    # Adiciona um healthcheck para o Docker saber quando o MySQL está pronto
    healthcheck: # <-- CORREÇÃO AQUI
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password"]
      interval: 5s
      timeout: 20s
      retries: 10

volumes:
  db_data:
